import Mathlib
import GaussianWhoWhere.Infinite.DensePeriodCoupler

/-!
# Kronecker density (Infinite L3, arithmetic half of C1)

Internalizes the arithmetic component of the dense-periods interface:

  `Irrational (a / b)  ⇒  TwoIncommensurablePeriodsGenerateDense a b`.

The proof routes through Mathlib's

  `dense_addSubgroupClosure_pair_iff
     : Dense ↑(AddSubgroup.closure {a, b}) ↔ Irrational (a / b)`

after identifying the `*`-form integer span used in
`TwoIncommensurablePeriodsGenerateDense` with
`AddSubgroup.closure {a, b}` as a set.

This concrete witness eliminates the abstract predicate
`TwoIncommensurablePeriodsGenerateDense` from the C3 pipeline as
soon as `Irrational (a / b)` is supplied (e.g. for
`a = log 2, b = log 3` via `irrational_log_ratio`-style inputs to be
provided separately).
-/

noncomputable section

namespace GaussianWhoWhere

/-- The integer period span as an explicit `AddSubgroup ℝ` carrier. -/
private def integerPeriodSpanAddSubgroup (a b : ℝ) : AddSubgroup ℝ :=
  { carrier := IntegerPeriodSpan a b
    zero_mem' := ⟨0, 0, by simp⟩
    add_mem' := by
      rintro x y ⟨m₁, n₁, rfl⟩ ⟨m₂, n₂, rfl⟩
      refine ⟨m₁ + m₂, n₁ + n₂, ?_⟩
      push_cast
      ring
    neg_mem' := by
      rintro x ⟨m, n, rfl⟩
      refine ⟨-m, -n, ?_⟩
      push_cast
      ring }

/-- The `*`-form integer period span coincides with the additive
subgroup generated by `{a, b}`. -/
theorem integerPeriodSpan_eq_addSubgroupClosure_pair (a b : ℝ) :
    IntegerPeriodSpan a b
      = (AddSubgroup.closure ({a, b} : Set ℝ) : Set ℝ) := by
  apply le_antisymm
  · -- IntegerPeriodSpan a b ⊆ closure {a, b}
    intro p hp
    rcases hp with ⟨m, n, rfl⟩
    have ha : a ∈ AddSubgroup.closure ({a, b} : Set ℝ) :=
      AddSubgroup.subset_closure (by simp)
    have hb : b ∈ AddSubgroup.closure ({a, b} : Set ℝ) :=
      AddSubgroup.subset_closure (by simp)
    change (m : ℝ) * a + (n : ℝ) * b ∈ AddSubgroup.closure ({a, b} : Set ℝ)
    rw [show (m : ℝ) * a = m • a from (zsmul_eq_mul a m).symm,
        show (n : ℝ) * b = n • b from (zsmul_eq_mul b n).symm]
    exact add_mem (zsmul_mem ha m) (zsmul_mem hb n)
  · -- closure {a, b} ⊆ IntegerPeriodSpan a b
    -- Use the explicit AddSubgroup whose carrier is IntegerPeriodSpan a b.
    have hsub : AddSubgroup.closure ({a, b} : Set ℝ)
        ≤ integerPeriodSpanAddSubgroup a b := by
      rw [AddSubgroup.closure_le]
      intro x hx
      rcases hx with hxa | hxb
      · exact ⟨1, 0, by rw [hxa]; push_cast; ring⟩
      · rw [Set.mem_singleton_iff] at hxb
        exact ⟨0, 1, by rw [hxb]; push_cast; ring⟩
    intro p hp
    exact hsub hp

/-- **Kronecker density: irrational ratio yields the dense
incommensurable-periods predicate.** -/
theorem twoIncommensurablePeriodsGenerateDense_of_irrational_div
    {a b : ℝ}
    (hirr : Irrational (a / b)) :
    TwoIncommensurablePeriodsGenerateDense a b := by
  -- Both shifts are nonzero: otherwise a/b is rational (0 or undefined-as-zero).
  have hb : b ≠ 0 := by
    intro hb0
    apply hirr
    refine ⟨0, ?_⟩
    simp [hb0]
  have ha : a ≠ 0 := by
    intro ha0
    apply hirr
    refine ⟨0, ?_⟩
    simp [ha0]
  refine ⟨ha, hb, ?_, ?_⟩
  · -- ∀ q : ℚ, a ≠ q * b
    intro q hq
    apply hirr
    refine ⟨q, ?_⟩
    rw [hq]
    field_simp
  · -- Dense (IntegerPeriodSpan a b)
    have hdenseClosure :
        Dense (AddSubgroup.closure ({a, b} : Set ℝ) : Set ℝ) :=
      dense_addSubgroupClosure_pair_iff.mpr hirr
    rw [show ({p : ℝ | ∃ m n : ℤ, p = (m : ℝ) * a + (n : ℝ) * b} : Set ℝ)
          = (AddSubgroup.closure ({a, b} : Set ℝ) : Set ℝ) from
        integerPeriodSpan_eq_addSubgroupClosure_pair a b]
    exact hdenseClosure

/-- Convenience alias accepting the longer "incommensurable +
irrational" hypothesis pack. The nonzero / non-rational-multiple
conjuncts are redundant here (they follow from `hirr`); the alias
exists for callers who already have those in hand. -/
theorem twoIncommensurablePeriodsGenerateDense_of_incommensurable
    {a b : ℝ}
    (_ha : a ≠ 0) (_hb : b ≠ 0)
    (_hincomm : ∀ q : ℚ, a ≠ (q : ℝ) * b)
    (hirr : Irrational (a / b)) :
    TwoIncommensurablePeriodsGenerateDense a b :=
  twoIncommensurablePeriodsGenerateDense_of_irrational_div hirr

end GaussianWhoWhere
